# Site settings
title: "Kristina P. Sinaga | AI Researcher & Applied Mathematics Ph.D."
description: "Expert in scalable AI models, federated learning, and Edge AI"
baseurl: ""
url: "https://kristinap09.github.io/"

# API Keys (Replace with your actual API key from ipapi.com)
ipapi_key: "dfa0986de9b5b2b65d2d2b9d5827c623"

# Theme settings
theme: jekyll-theme-minimal
markdown: kramdown
plugins:
  - jekyll-seo-tag

# Author information
author:
  name: Kristina P. Sinaga
  email: kristinasinaga41@gmail.com

# Social links
social:
  linkedin: kristina-p-sinaga-0ba152309
  github: KristinaP09
  twitter: NeuralGlowAI
  scholar: yNWQLYAAAAAJ
